### ISSUE TITLE
Bug in the implementation of DcorrX?

### ISSUE THREAD

**Issue by ninamiolane** [neurodata/hyppo#115]
My issue is about the implementation of independence test with DcorrX:
- `DcorrX(max_lag=0)` does not give the same result as `Dcorr`
- `DcorrX(max_lag=0)` gives a test statistic that is exactly 0.
Would you know why? Thank you in advance!

I have a minimal example below, with 4 samples. I also encountered the same error with higher sample size, for example a sample of size 15.

#### Reproducing code example:
```
import numpy as np

from hyppo.independence import dcorr
from hyppo.time_series import dcorrx

x = np.array([
            [0.95476444],
            [0.36741182],
            [0.37473209],
            [-0.62469378]])
y = np.array([
            [0.86515308],
            [-0.01985114],
            [0.21544295],
            [1.56443374]])
stat, p = dcorr.Dcorr().test(x, y)
statx, px, _ = dcorrx.DcorrX(max_lag=0).test(x, y)

assert stat == statx
```
#### Error
The above code gives the error:
```
AssertionError: -0.5000000000000935 != 0.0
```

#### Version information

- OS: Ubuntu 18.04.3 LTS
- Python Version 3.7.7 
- Package Version 0.1.2

**Comment by rmehta004** [comment]
Thank you for the detailed description of the error! Both the population DCorr and MGC values are bounded between 0 and 1. Negative values in the DCorr and MGC sample statistics are a consequence of our unbiased estimation of the population value when it is truly close to 0, as in the case above (I assume these arrays are independent random draws, so the population DCorr is 0). In DCorrX, because we are adding together multiple DCorr statistics, for the sake of interpretability, we clip the negative values of the statistics to be 0 (-0.5 is clipped to 0 in the above example). Thus, they are slightly positively biased when the population DCorr is small. This bias decreases both with increasing sample size and increasing degree of dependence, and will not change affect the p-value for any sample. If you try an example where `x` and `y` are more heavily dependent, the values will be equal. We will make this point more clear in our documentation.

**Comment by ninamiolane** [comment]
Thank you for your quick answer!

I understand that DCorr and DCorrX should have given the (same negative) value - since, in this specific case, `max_lag=0` for DcorrX. But DCorrX has an additional clipping operation that brings its negative value (coming from an unbiased estimation) to 0.

I have the same problem with MGC and MGCX: I assume this is the same thing?

**Comment by rmehta004** [comment]
Yes you are exactly right. I actually discussed with the team and based on their feedback, I removed the negative value clipping in dcorrx and mgcx to make them unbiased. As before, the p-values for any sample size or distribution will remain the same in either scenario, but now you will have both DCorr = DCorrX(max_lag=0) and MGC = MGCX(max_lag=0) for all distributions and sample sizes. The change is reflected in the master branch - please let me know if you have any more questions!

**Comment by ninamiolane** [comment]
That's awesome, thank you very much! (I'm using the PyPI version, I think the changes will be reflected there too?)

**Comment by sampan501** [comment]
it should take a little longer since I accumulate multiple changes before releasing. However github install instructions are easy and also here: https://hyppo.neurodata.io/install.html#install-from-github
