### ISSUE TITLE
Where do non-distance inputs get converted to distance in `discrim`?

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/hyppo#139]
If I pass in a non-distance matrix input to discriminability, I am trying to find where that input is converted to a distance/dissimilarity. Can't for the life of me find it in the code, can someone point me in the right direction?

@sampan501 @jdey4

**Comment by sampan501** [comment]
So I believe that, and @jdey4 can correct me if I'm wrong, uses euclidean distance if you pass in data matrices. Otherwise, you precompute the distance matrix and pass it into the function, setting `is_dist` to `True`. We will probably change this functionality in the future to put it more in line with the other functions in `hyppo`

**Comment by bdpedigo** [comment]
can you point me to where in the code this happens though?

**Comment by bdpedigo** [comment]
but agree that a metric function would make it more inline with other stuff in the package

**Comment by sampan501** [comment]
Here: https://github.com/neurodata/hyppo/blob/2f4406eb175446d683d0d052bf7befa57b5c801f/hyppo/discrim/_utils.py#L63

and here isolates are removed:
https://github.com/neurodata/hyppo/blob/2f4406eb175446d683d0d052bf7befa57b5c801f/hyppo/discrim/_utils.py#L57

**Comment by bdpedigo** [comment]
thanks! should I open an issue for the metrics thing?
