### ISSUE TITLE
Distance Correlation (Dcorr) test statistic

### ISSUE THREAD

**Issue by dolevbas** [neurodata/hyppo#199]
Hi,

Thanks for the nice package !

As for the Distance Correlation (Dcorr) test statistic calculation, I believe (if I'm not wrong) that the value at the 'bias=True' scenario, should be the square root of the value it currently returns.

All the best,
Dolev

**Comment by sampan501** [comment]
Hello, thank you for your interest in the package. It turns out that taking the square root or not really doesn't matter, as long as you use Dcorr vs Dcorr^2 consistently. More crucially, the p-value is unaffected by using either method since it is unaffected under permutation. We stuck with this and probably will in the future since many of our tests depend on Dcorr^2 and will be invalid when taking the square root.

**Comment by dolevbas** [comment]
Great, thanks !
