### ISSUE TITLE
Reproducibility of tests not fully functional

### ISSUE THREAD

**Issue by kareef928** [neurodata/hyppo#228]
Seems that we still do not get consistent reproducibility after #212, I think it has something to do with [PermGroups](https://github.com/neurodata/hyppo/blob/771bda8f029f95073613bed18709d80d90ef3a2d/hyppo/tools/common.py#L346) but I do not quite understand its behavior.

**Comment by rflperry** [comment]
PermGroups is a wrapper of the default permutation to allow for more special permutations if `perm_blocks` is given. The default is `perm_blocks=None` in which case it should just do a regular permutation ([this line](https://github.com/neurodata/hyppo/blob/771bda8f029f95073613bed18709d80d90ef3a2d/hyppo/tools/common.py#L358)). 

There are two issues/ways to fix the situation as I see it for the default permutation behavior (the special tree permutation behavior would require something else at [this line](https://github.com/neurodata/hyppo/blob/771bda8f029f95073613bed18709d80d90ef3a2d/hyppo/tools/common.py#L334)).

1. [This line](https://github.com/neurodata/hyppo/blob/771bda8f029f95073613bed18709d80d90ef3a2d/hyppo/tools/common.py#L370) has the correct reproducibility logic but is never called since the if statement should read `if permuter is None` to be correct, but also `permuter` is never None since as we see in [this line](https://github.com/neurodata/hyppo/blob/771bda8f029f95073613bed18709d80d90ef3a2d/hyppo/tools/common.py#L452) even when `perm_blocks=None` the `PermGroups` object is still created and passed in. An if statement could be added to otherwise set `permuter=None`.
2. The `PermGroups` object `__call__` function could be passed in the `rng` parameter to seed the random number generator by rewriting [this line](https://github.com/neurodata/hyppo/blob/771bda8f029f95073613bed18709d80d90ef3a2d/hyppo/tools/common.py#L356) as `order = rng.permutation(n)`. You could then optionally also extend this `rng` seed parameter to the `_PermTree` object to make its randomness reproducible.

I'd recommend doing the 1st and the first half of the 2nd.
